version: '2'
services:
  photonbbs:
    build: .
    image: fewtarius/photonbbs
    hostname: photonbbs
    network_mode: bridge
    devices:
    - /dev:/dev:rwm
    - /lib/modules:/lib/modules:rwm
    ports:
    - 23:23/tcp
    privileged: true
    tty: true
    volumes:
    - appdata:/appdata:rw

volumes:
  appdata:
    driver: rancher-nfs
    driver_opts:
      onRemove: retain
